const $=s=>document.querySelector(s);let db=null,user=null,vehicles=[],readings=[];
const config=()=>({url:localStorage.getItem('sb_url'),key:localStorage.getItem('sb_key')});
function initClient(){const c=config();if(!c.url||!c.key)return false;db=supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true}});return true}
function show(id){['setup','auth','app'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));$('#logout').classList.toggle('hidden',id!=='app')}
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const n=x=>new Intl.NumberFormat('de-DE').format(Math.round(x||0));const money=x=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(x||0);const iso=d=>new Date(d+'T12:00:00');const days=(a,b)=>Math.max(0,Math.round((iso(b)-iso(a))/86400000));
async function start(){if(!initClient()){show('setup');return}const {data:{session}}=await db.auth.getSession();if(session){user=session.user;show('app');await load()}else show('auth');db.auth.onAuthStateChange(async(_,s)=>{if(s&&!user){user=s.user;show('app');await load()}if(!s){user=null;show('auth')}})}
$('#saveSetup').onclick=()=>{localStorage.setItem('sb_url',$('#sbUrl').value.trim().replace(/\/$/,''));localStorage.setItem('sb_key',$('#sbKey').value.trim());location.reload()};
$('#resetConfig').onclick=()=>{localStorage.removeItem('sb_url');localStorage.removeItem('sb_key');location.reload()};
async function auth(mode){$('#authMsg').textContent='';const email=$('#email').value.trim(),password=$('#password').value;const r=mode==='in'?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password});$('#authMsg').textContent=r.error?r.error.message:(r.data.session?'Angemeldet.':'Konto angelegt. Bitte ggf. Bestätigungs-E-Mail öffnen.')}
$('#login').onclick=()=>auth('in');$('#signup').onclick=()=>auth('up');$('#logout').onclick=()=>db.auth.signOut();$('#refresh').onclick=()=>load();
async function seed(){const {data}=await db.from('vehicles').select('id').limit(1);if(data?.length)return;const defaults=[{name:'Seat Ateca',short_name:'Ateca',contract_start:'2023-06-11',contract_end:'2027-06-11',start_odometer:0,total_km:50000,tolerance_km:2500,overage_eur_km:.1214,underage_eur_km:.0559},{name:'Cupra Born',short_name:'Born',contract_start:'2023-10-16',contract_end:'2027-10-16',start_odometer:0,total_km:50000,tolerance_km:2500,overage_eur_km:.0916,underage_eur_km:.0417}].map(v=>({...v,user_id:user.id}));const {data:vs,error}=await db.from('vehicles').insert(defaults).select();if(error)throw error;await db.from('readings').insert([{user_id:user.id,vehicle_id:vs[0].id,reading_date:'2023-06-11',odometer:0,note:'Übergabe'},{user_id:user.id,vehicle_id:vs[0].id,reading_date:'2026-09-03',odometer:41384,note:'Aktueller Stand'},{user_id:user.id,vehicle_id:vs[1].id,reading_date:'2023-10-16',odometer:0,note:'Übergabe'},{user_id:user.id,vehicle_id:vs[1].id,reading_date:'2026-09-18',odometer:41273,note:'Aktueller Stand'}])}
async function load(){try{$('#sync').textContent='● synchronisiere…';await seed();let vr=await db.from('vehicles').select('*').order('created_at');if(vr.error)throw vr.error;vehicles=vr.data;let rr=await db.from('readings').select('*').order('reading_date',{ascending:false}).order('created_at',{ascending:false});if(rr.error)throw rr.error;readings=rr.data;render();$('#sync').textContent='● synchronisiert'}catch(e){$('#sync').textContent='● Fehler: '+e.message}}
function calc(v){const rs=readings.filter(r=>r.vehicle_id===v.id).sort((a,b)=>a.reading_date.localeCompare(b.reading_date));const latest=rs.at(-1)||{reading_date:v.contract_start,odometer:v.start_odometer};const elapsed=days(v.contract_start,latest.reading_date),duration=days(v.contract_start,v.contract_end),left=days(latest.reading_date,v.contract_end),driven=latest.odometer-v.start_odometer,expected=v.total_km*Math.min(1,elapsed/duration),forecast=elapsed? v.start_odometer+(driven/elapsed)*duration:latest.odometer,max=v.start_odometer+v.total_km+v.tolerance_km,over=Math.max(0,forecast-max),under=Math.max(0,v.start_odometer+v.total_km-forecast);return{latest,driven,expected,delta:driven-expected,forecast,left,over,cost:over*v.overage_eur_km,under,refund:under*v.underage_eur_km,allowed:left?Math.max(0,v.total_km-driven)/left:0,progress:driven/v.total_km}}
function render(){const select=$('#vehicleSelect');select.innerHTML=vehicles.map(v=>`<option value="${v.id}">${esc(v.short_name)}</option>`).join('');$('#readingDate').value=new Date().toISOString().slice(0,10);$('#cards').innerHTML=vehicles.map(v=>{const c=calc(v),warn=c.forecast>v.start_odometer+v.total_km+v.tolerance_km;return `<article class="vehicle"><div class="vehicle-top"><div><small>${esc(v.short_name)}</small><h2>${esc(v.name)}</h2></div><button class="ghost edit" data-id="${v.id}">Bearbeiten</button></div><div class="hero">${n(c.latest.odometer)} km</div><small>Stand ${new Date(c.latest.reading_date+'T12:00:00').toLocaleDateString('de-DE')}</small><div class="bar"><i style="width:${Math.min(100,c.progress*100)}%"></i></div><span class="badge ${warn?'warn':''}">${warn?'Mehrkosten prognostiziert':'im kostenfreien Bereich prognostiziert'}</span><div class="metrics"><div class="metric"><span>Soll heute</span><b>${n(c.expected)} km</b></div><div class="metric"><span>Abweichung</span><b>${c.delta>=0?'+':''}${n(c.delta)} km</b></div><div class="metric"><span>Endprognose</span><b>${n(c.forecast)} km</b></div><div class="metric"><span>Erlaubt / Resttag</span><b>${c.allowed.toFixed(1)} km</b></div><div class="metric"><span>Mehrkosten Prognose</span><b class="cost">${money(c.cost)}</b></div><div class="metric"><span>Erstattung Prognose</span><b>${money(c.refund)}</b></div></div></article>`}).join('');document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openEdit(b.dataset.id));$('#history').innerHTML=readings.slice(0,20).map(r=>{const v=vehicles.find(v=>v.id===r.vehicle_id);return `<div class="history-item"><div><b>${n(r.odometer)} km</b><br><small>${esc(v?.short_name)} · ${new Date(r.reading_date+'T12:00:00').toLocaleDateString('de-DE')} ${r.note?'· '+esc(r.note):''}</small></div><button class="ghost del" data-id="${r.id}">×</button></div>`}).join('')||'<p class="muted">Noch keine Einträge.</p>';document.querySelectorAll('.del').forEach(b=>b.onclick=()=>removeReading(b.dataset.id))}
$('#readingForm').onsubmit=async e=>{e.preventDefault();$('#saveMsg').textContent='Speichere…';const payload={user_id:user.id,vehicle_id:$('#vehicleSelect').value,reading_date:$('#readingDate').value,odometer:+$('#odometer').value,note:$('#note').value.trim()||null};const {error}=await db.from('readings').insert(payload);$('#saveMsg').textContent=error?error.message:'Gespeichert und synchronisiert.';if(!error){e.target.reset();await load()}}
async function removeReading(id){if(!confirm('Eintrag wirklich löschen?'))return;await db.from('readings').delete().eq('id',id);await load()}
function openEdit(id){const v=vehicles.find(x=>x.id===id);$('#editId').value=id;$('#editName').value=v.name;$('#editShort').value=v.short_name;$('#editStart').value=v.contract_start;$('#editEnd').value=v.contract_end;$('#editTotal').value=v.total_km;$('#editTolerance').value=v.tolerance_km;$('#editOver').value=v.overage_eur_km;$('#editUnder').value=v.underage_eur_km;$('#editDialog').showModal()}
$('#saveVehicle').onclick=async e=>{e.preventDefault();const id=$('#editId').value,p={name:$('#editName').value,short_name:$('#editShort').value,contract_start:$('#editStart').value,contract_end:$('#editEnd').value,total_km:+$('#editTotal').value,tolerance_km:+$('#editTolerance').value,overage_eur_km:+$('#editOver').value,underage_eur_km:+$('#editUnder').value};const {error}=await db.from('vehicles').update(p).eq('id',id);if(error)return alert(error.message);$('#editDialog').close();await load()};
start();
