
const $ = s => document.querySelector(s);
let db=null, user=null, vehicles=[], readings=[], currentView='active';
const config=()=>({url:localStorage.getItem('sb_url'),key:localStorage.getItem('sb_key')});
function initClient(){const c=config();if(!c.url||!c.key)return false;db=supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true}});return true}
function show(id){['setup','auth','app'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));$('#logout').classList.toggle('hidden',id!=='app')}
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const n=x=>new Intl.NumberFormat('de-DE').format(Math.round(x||0));
const money=x=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(x||0);
const iso=d=>new Date(d+'T12:00:00');
const days=(a,b)=>Math.max(0,Math.round((iso(b)-iso(a))/86400000));
function normalizeDriveType(value) {
  const allowed = ['electric', 'petrol', 'diesel', 'hybrid', 'other'];
  return allowed.includes(value) ? value : 'other';
}
async function start(){if(!initClient()){show('setup');return}const {data:{session}}=await db.auth.getSession();if(session){user=session.user;show('app');await load()}else show('auth');db.auth.onAuthStateChange(async(_,s)=>{if(s&&!user){user=s.user;show('app');await load()}if(!s){user=null;show('auth')}})}
$('#saveSetup').onclick=()=>{localStorage.setItem('sb_url',$('#sbUrl').value.trim().replace(/\/$/,''));localStorage.setItem('sb_key',$('#sbKey').value.trim());location.reload()};
$('#resetConfig').onclick=()=>{localStorage.removeItem('sb_url');localStorage.removeItem('sb_key');location.reload()};
async function auth(mode){$('#authMsg').textContent='';const email=$('#email').value.trim(),password=$('#password').value;const r=mode==='in'?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password});$('#authMsg').textContent=r.error?r.error.message:(r.data.session?'Angemeldet.':'Konto angelegt. Bitte ggf. Bestätigungs-E-Mail öffnen.')}
$('#login').onclick=()=>auth('in');$('#signup').onclick=()=>auth('up');$('#logout').onclick=()=>db.auth.signOut();$('#refresh').onclick=()=>load();
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));render()});
async function load(){try{$('#sync').textContent='● synchronisiere…';const vr=await db.from('vehicles').select('*').order('created_at');if(vr.error)throw vr.error;vehicles=vr.data;const rr=await db.from('readings').select('*').order('reading_date',{ascending:false}).order('created_at',{ascending:false});if(rr.error)throw rr.error;readings=rr.data;render();$('#sync').textContent='● synchronisiert'}catch(e){$('#sync').textContent='● Fehler: '+e.message}}
function calc(v){const rs=readings.filter(r=>r.vehicle_id===v.id).sort((a,b)=>a.reading_date.localeCompare(b.reading_date));const latest=rs.at(-1)||{reading_date:v.contract_start,odometer:v.start_odometer};const elapsed=days(v.contract_start,latest.reading_date),duration=Math.max(1,days(v.contract_start,v.contract_end)),left=days(latest.reading_date,v.contract_end),driven=latest.odometer-v.start_odometer,expected=v.total_km*Math.min(1,elapsed/duration),forecast=elapsed?v.start_odometer+(driven/elapsed)*duration:latest.odometer,max=v.start_odometer+v.total_km+v.tolerance_km,over=Math.max(0,forecast-max),under=Math.max(0,v.start_odometer+v.total_km-forecast);return{latest,driven,expected,delta:driven-expected,forecast,left,over,cost:over*v.overage_eur_km,under,refund:under*v.underage_eur_km,allowed:left?Math.max(0,v.total_km-driven)/left:0,progress:Math.max(0,driven/v.total_km)}}
function render(){const active=vehicles.filter(v=>v.is_active!==false), shown=vehicles.filter(v=>currentView==='active'?v.is_active!==false:v.is_active===false);$('#readingPanel').classList.toggle('hidden',currentView==='archived'||!active.length);$('#vehicleSelect').innerHTML=active.map(v=>`<option value="${v.id}">${esc(v.short_name)}</option>`).join('');if(!$('#readingDate').value)$('#readingDate').value=new Date().toISOString().slice(0,10);$('#cards').innerHTML=shown.length?shown.map(cardHtml).join(''):`<div class="panel empty">${currentView==='active'?'Noch kein aktives Fahrzeug. Über „+ Fahrzeug“ kannst du eines anlegen.':'Noch keine archivierten Fahrzeuge.'}</div>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openVehicle(b.dataset.edit));document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>setActive(b.dataset.archive,false));document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>setActive(b.dataset.restore,true));const ids=new Set(shown.map(v=>v.id));const visible=readings.filter(r=>ids.has(r.vehicle_id));$('#history').innerHTML=visible.slice(0,30).map(r=>{const v=vehicles.find(v=>v.id===r.vehicle_id);return `<div class="history-item"><div><b>${n(r.odometer)} km</b><br><small>${esc(v?.short_name)} · ${iso(r.reading_date).toLocaleDateString('de-DE')} ${r.note?'· '+esc(r.note):''}</small></div><button class="ghost" data-delete-reading="${r.id}">×</button></div>`}).join('')||'<p class="muted">Keine Einträge in dieser Ansicht.</p>';document.querySelectorAll('[data-delete-reading]').forEach(b=>b.onclick=()=>removeReading(b.dataset.deleteReading))}
function cardHtml(v){const c=calc(v),arch=v.is_active===false,warn=c.forecast>v.start_odometer+v.total_km+v.tolerance_km;return `<article class="vehicle"><div class="vehicle-top"><div><small>${esc(v.short_name)}</small><h2>${esc(v.name)}</h2></div><div class="vehicle-actions"><button class="ghost" data-edit="${v.id}">Bearbeiten</button>${arch?`<button data-restore="${v.id}">Reaktivieren</button>`:`<button class="danger" data-archive="${v.id}">Archivieren</button>`}</div></div><div class="hero">${n(c.latest.odometer)} km</div><small>Stand ${iso(c.latest.reading_date).toLocaleDateString('de-DE')}</small><div class="bar"><i style="width:${Math.min(100,c.progress*100)}%"></i></div><span class="badge ${arch?'archive':warn?'warn':''}">${arch?'archiviert':warn?'Mehrkosten prognostiziert':'im kostenfreien Bereich prognostiziert'}</span><div class="metrics"><div class="metric"><span>Soll heute</span><b>${n(c.expected)} km</b></div><div class="metric"><span>Abweichung</span><b>${c.delta>=0?'+':''}${n(c.delta)} km</b></div><div class="metric"><span>Endprognose</span><b>${n(c.forecast)} km</b></div><div class="metric"><span>Erlaubt / Resttag</span><b>${c.allowed.toFixed(1)} km</b></div><div class="metric"><span>Mehrkosten Prognose</span><b class="cost">${money(c.cost)}</b></div><div class="metric"><span>Erstattung Prognose</span><b>${money(c.refund)}</b></div></div></article>`}
$('#readingForm').onsubmit=async e=>{e.preventDefault();$('#saveMsg').textContent='Speichere…';const p={user_id:user.id,vehicle_id:$('#vehicleSelect').value,reading_date:$('#readingDate').value,odometer:+$('#odometer').value,note:$('#note').value.trim()||null};const {error}=await db.from('readings').insert(p);$('#saveMsg').textContent=error?error.message:'Gespeichert und synchronisiert.';if(!error){$('#odometer').value='';$('#note').value='';await load()}}
async function removeReading(id){if(!confirm('Ablesung wirklich löschen?'))return;const {error}=await db.from('readings').delete().eq('id',id);if(error)alert(error.message);else await load()}
$('#addVehicle').onclick=()=>openVehicle();$('#cancelVehicle').onclick=()=>$('#vehicleDialog').close();
function openVehicle(id=null){const v=vehicles.find(x=>x.id===id);$('#dialogTitle').textContent=v?'Fahrzeug bearbeiten':'Neues Fahrzeug';$('#editId').value=v?.id||'';$('#editName').value=v?.name||'';$('#editShort').value=v?.short_name||'';$('#editStart').value=v?.contract_start||'';$('#editEnd').value=v?.contract_end||'';$('#editStartKm').value=v?.start_odometer??0;$('#editTotal').value=v?.total_km??50000;$('#editTolerance').value=v?.tolerance_km??2500;$('#editOver').value=v?.overage_eur_km??0;$('#editUnder').value=v?.underage_eur_km??0;const driveTypeField = $('#editDriveType');
if (driveTypeField) {
  driveTypeField.value = normalizeDriveType(v?.drive_type);
}
                              $('#vehicleDialog').showModal()}
$('#vehicleForm').onsubmit=async e=>{e.preventDefault();const id=$('#editId').value,p={user_id:user.id,name:$('#editName').value.trim(),short_name:$('#editShort').value.trim(),contract_start:$('#editStart').value,contract_end:$('#editEnd').value,start_odometer:+$('#editStartKm').value,total_km:+$('#editTotal').value,tolerance_km:+$('#editTolerance').value,overage_eur_km:+$('#editOver').value,underage_eur_km:+$('#editUnder').value,
drive_type:normalizeDriveType($('#editDriveType')?.value)};if(!id)p.is_active=true;const q=id?db.from('vehicles').update(p).eq('id',id):db.from('vehicles').insert(p);const {error}=await q;if(error)return alert(error.message);$('#vehicleDialog').close();await load()};
async function setActive(id,on){if(!on&&!confirm('Fahrzeug archivieren? Alle Ablesungen bleiben erhalten.'))return;const {error}=await db.from('vehicles').update({is_active:on,archived_at:on?null:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else await load()}
window.getFuhrparkVehicles = function () {
  return Array.isArray(vehicles)
    ? vehicles
    : [];
};
start();
